### ISSUE TITLE
Creating a tab from scratch

### ISSUE THREAD

**Issue by Perlence** [Perlence/PyGuitarPro#1]
@Kochevar wrote:

> I'm kinda new to python and trying to write a code that writes some chords into a GP file. Is it possible to make a new file from zero? So far I'm only able to parse an existing GP file and then change the notes.

**Comment by Perlence** [comment]
Hello. Yes, I admit, creating a blank tab is not as easy as it should be. I've made some changes in the develop branch to make better default values.

So, pull the latest changes from develop and try this code to make a tab with one track and one blank measure:

```python
import guitarpro

song = guitarpro.base.Song()
track = guitarpro.base.Track(name='Track 1')
track.strings = [guitarpro.base.GuitarString(n, v)
                 for n, v in [(1, 64), (2, 59), (3, 55),
                              (4, 50), (5, 45), (6, 40)]]
measure = guitarpro.base.Measure()
measure.voices = [guitarpro.base.Voice(), guitarpro.base.Voice()]
for voice in measure.voices:
    voice.addBeat(guitarpro.base.Beat())
track.addMeasure(measure)
song.addTrack(track)

guitarpro.write(song, 'blank.gp5')
```

**Comment by Kochevar** [comment]
Thanks!

**Comment by iampasan** [comment]
Hi! 
I'm trying to write a tab from scratch from a music21 stream and an array of finger positions for the relevant stream, could you update this code to match the latest version? 
Thanks!
