### ISSUE TITLE
Printing measure sequence

### ISSUE THREAD

**Issue by Chutlhu** [Perlence/PyGuitarPro#13]
Dear pyGuitarPro staff,
first of all I really want to thank you for this amazing code.
Second, is there an easy to print the exact measure sequence considering the various type of repetition available in GP?
Example:
1---2---3---4---[5---6---7---8]x2---9---10---11---12
I would like to obtain a list as follows:
1,2,3,4,5,6,7,8,5,6,7,8,9,10,11,12

In other words, how to easily serialize a tab?

I need it to compute the exact time location of some parts of the wave rendered by guitarpro.

thank you very much,

**Comment by kevinhynes** [comment]
I'm not affiliated with the creation of PyGuitarPro... and I'm not sure exactly what you're asking, but the information regarding "repeat groups" is stored in MeasureHeader.isRepeatOpen and MeasureHeader.repeatClose.  Each Song has a list of Tracks (Song.tracks), each Track has a list of Measures (Track.measures), and each Measure has a reference to its' MeasureHeader (Measure.header).  So as you're iterating through a track's measures, you can look at the measure's header to figure out if the measure is opening or closing a repeat group.

**Comment by kevinhynes** [comment]
@Chutlhu here is a quick gist of something I'm working on that might help you.  https://gist.github.com/kevinhynes/68b3df3caf0c1f951f03c29fdeb75117

**Comment by Perlence** [comment]
Thanks for your patience. What you are asking for is not implemented in PyGuitarPro, i.e. there's no such function currently available, but you have all the data you'd need to implement it. Thanks to @kevinhynes for outlining the algorithm!
