### ISSUE TITLE
Visibility of the project: Adopting Kaitai Struct format

### ISSUE THREAD

**Issue by MZehren** [Perlence/PyGuitarPro#14]
Hello,

After seeing multiple projects on Github to parse Guitar pro files in different languages, and none of them which would have been easily integrated into my code (until I found yours), I wonder if we could do things in a better way: During my search, I found the project https://kaitai.io which offers a standard way of describing a binary file and then compile a parser for this file in multiple languages (Python is part of the languages supported).

Have you considered moving the part of your code doing the parsing into a general library such as this one? This would solve the issue of all the duplicated projects doing the same parsing in different languages while enjoying the visibility of Kaitai library. It would also help to get more people together to include newer GP formats you could use for free.

I started writing the GP5 specifications in Kaitai in my own fork of their shared library of supported format before I found your project --- which actually does what I want in native Python. Maybe we could unit our force and create a GP specification in Kaitai to end with this endless loop of duplicated code?

**Comment by Perlence** [comment]
Thanks, I haven't heard of Kaitai before, its premise looks interesting. However, I don't think that PyGuitarPro will benefit from adopting it. I'm looking forward to see your GP specification in Kaitai complete.

**Comment by mauricek** [comment]
As I am just in the process of getting a GP parser to work in C++, is there a chance to see your work in progress? In the long term, that might make my efforts superfluous.
