### ISSUE TITLE
models.Duration.fromTime wrong answer for dotted quintuplets

### ISSUE THREAD

**Issue by Cortexelus** [Perlence/PyGuitarPro#16]
![image](https://user-images.githubusercontent.com/2453861/94221369-f4a34600-feb8-11ea-84a9-268461d3b934.png)

`gp.models.Duration.fromTime(576)` 
is a dotted eighth quintuplet, but it falsely returns
`Duration(value=8, isDotted=True, tuplet=Tuplet(enters=1, times=1))`
 its correct value should be
`Duration(value=8, isDotted=True, tuplet=Tuplet(enters=5, times=4))`

Similar problem for all dotted quintuplets

**Comment by Perlence** [comment]
Hello CJ!

Thanks for noticing. I've fixed this in 1491212ff58410d830d8256498f9042cd969bee5. I'm going to make a new release soon.

**Comment by Cortexelus** [comment]
Amazing, thank you for being so responsive!
