### ISSUE TITLE
Mysterious Pinch Harmonic appears out of nowhere

### ISSUE THREAD

**Issue by Cortexelus** [Perlence/PyGuitarPro#17]
`Frank Zappa - Watermelon In Easter Hay (2).gp4`
https://drive.google.com/file/d/1ZoQlQf4PXwJrY0DlI3arbgg4e3hnzNi_/view?usp=sharing

Load this file in Guitar Pro. Notice there are no pinch harmonics at the beginning of the 16th measure of the first track.
![image](https://user-images.githubusercontent.com/2453861/94286027-79767a00-ff22-11ea-8554-78bf0e245185.png)

Load it with `gp.parse`. A pinch harmonic appears out of nowhere!
![image](https://user-images.githubusercontent.com/2453861/94285883-4e8c2600-ff22-11ea-9a42-912408c75092.png)

**Comment by Perlence** [comment]
I'm afraid it's actually there. Here's the screenshot from Guitar Pro 5:

![bar16](https://user-images.githubusercontent.com/1044300/94296456-89ff1280-ff6b-11ea-8635-61f1b0a09499.png)

**Comment by Cortexelus** [comment]
Oh hm. I guess it's a bug with GuitarPro7. Okay thanks!

**Comment by Perlence** [comment]
No problem!
