### ISSUE TITLE
ValueError: 9 is not a valid ChordExtension

### ISSUE THREAD

**Issue by giona69** [Perlence/PyGuitarPro#18]
this gp5 gives me an error.

GP7.5 reads it, and other gp reader can do it ... maybe it's a bug?

[My-Funny-Valentine-chord-melody.gp5.zip](https://github.com/Perlence/PyGuitarPro/files/5394055/My-Funny-Valentine-chord-melody.gp5.zip)

**Comment by Perlence** [comment]
Hello @giona69! It does look like a bug, but I'm not sure yet what's the best way to handle it. For now, you can apply the following workaround in your copy of PyGuitarPro:

```diff
diff --git a/guitarpro/models.py b/guitarpro/models.py
index 5a892dc..f9a74d7 100644
--- a/guitarpro/models.py
+++ b/guitarpro/models.py
@@ -1254,6 +1254,7 @@ class ChordExtension(Enum):
 
     #: Ninth chord.
     ninth = 1
+    ninth2 = 9
 
     #: Eleventh chord.
     eleventh = 2
```

**Comment by Perlence** [comment]
I've pushed the commit 493158e that resolves this issue. Thanks for reporting!

**Comment by giona69** [comment]
that's great, thanks a lot for your quick fix!!
