### ISSUE TITLE
gp and gpx

### ISSUE THREAD

**Issue by giona69** [Perlence/PyGuitarPro#19]
no plans to read gp and gpx? ora any suggestions on libraries out there to read them? any language

thanks

**Comment by Perlence** [comment]
Hello @giona69! I don't plan to support gpx and gp in PyGuitarPro.

Guitar Pro 7's gp file is a plain ZIP archive. You can unpack it and find the `score.gpif` file which is an XML file. You can parse `score.gpif` with [ElementTree](https://docs.python.org/3/library/xml.etree.elementtree.html).

gpx file is a custom archive that also contains the `score.gpif` XML file. You can try to unpack the gpx file by using [this module](https://github.com/Perlence/PyGuitarPro/blob/feature/gpx/guitarpro/gpx.py).

**Comment by giona69** [comment]
great suggestions thank you very much!
