### ISSUE TITLE
Playing guitarPro files

### ISSUE THREAD

**Issue by domas94** [Perlence/PyGuitarPro#21]
Hi Perlence,

is it possible to play guitarPro files with your library? If not do you have any suggestions?

Thank you.

**Comment by Perlence** [comment]
Hello @domas94! No, it's not possible to play Guitar Pro files with PyGuitarPro only.

alphaTab seems to support MIDI output https://github.com/CoderLine/alphaTab/blob/d9c7834/src/midi/MidiFile.ts#L54.

Also, check out this project https://github.com/rageagainsthepc/GuitarPro-to-Midi.

**Comment by domas94** [comment]
Thank you for your answer
