### ISSUE TITLE
Duration issue

### ISSUE THREAD

**Issue by DiXcipuli** [Perlence/PyGuitarPro#23]
Hi, it seems like the library does not make any differences between a dotted and a double dotted note:

For this two-bars tab:
![duration](https://user-images.githubusercontent.com/33719470/126080986-0b01ef83-5193-4835-b4fd-0fc8ac569060.png)

And with this code:
```
import guitarpro as pygp

song = pygp.parse("test.gp3")
for measure in song.tracks[0].measures:
    for voice in measure.voices:
        for beat in voice.beats:
            if beat.notes:
                print(beat.duration.time)
```

It outputs both:

```
1440
1440
```

Am I missusing something? How could I achieve writing a double dotted note?

Thanks!

**Comment by Perlence** [comment]
Hello @DiXcipuli! Could you share the test.gp3, please?

**Comment by DiXcipuli** [comment]
Thanks for the responsivity!

Well, while I was about to upload test.gp3, I just opened it to check it, and I was surprised to see that the double-dotted note had been transform to a single-dotted one!

It seems to be a known issue in TuxGuitar (a score editor for Linux): https://sourceforge.net/p/tuxguitar/bugs/97/

So, saving my Tab in .tg file keeps that double dot, but saving in .gp3-4-5 removes it. (So is it inherent to gp format?)
Unfortunatelly, after installing guitarpro7 on Ubuntu, and trying to export my tab into gp5 file, I get a warning:
 - Double dot not exported in bar 1

So I have no way to try a tab with a double-dotted note in it!
If someone would have a sample I would be in!

Could you just tell me how is supposed to be represented a double-dotted note in the lib, as I only see a field:
`isDotted: bool = False` in the class duration

Thanks!

**Comment by Perlence** [comment]
Unfortunately, there's no way to represent a double-dotted note in Guitar Pro 3–5. And while PyGuitarPro supports only Guitar Pro 3–5, you cannot set a double-dotted note in PyGuitarPro.
