### ISSUE TITLE
Support to read PowerTab (.ptb) files

### ISSUE THREAD

**Issue by ventralnet** [Perlence/PyGuitarPro#24]
Any chance to support power tab files?

**Comment by ventralnet** [comment]
I quickly made something to parse meta data from ptb files for my purposes (organizing my tab library)

https://github.com/ventralnet/PowerTabParser

**Comment by Perlence** [comment]
Hello @ventralnet! I don't plan to implement the power tab support in PyGuitarPro.

**Comment by ventralnet** [comment]
Ok thanks
