### ISSUE TITLE
Incorrect calculation of duration for grace notes

### ISSUE THREAD

**Issue by cwitkowitz** [Perlence/PyGuitarPro#34]
If the aim of `GraceEffect.durationTime` is to return the time of the grace note in ticks, I believe the contents of the function are incorrect:
https://github.com/Perlence/PyGuitarPro/blob/c2044d99fb5b9098a738ffd1b2c305daca064d83/guitarpro/models.py#L980
and should be `int(Duration.quarterTime * 4 / self.duration)` instead. This is also reflected in parts of the `Duration` class.

**Comment by cwitkowitz** [comment]
Thanks for fixing this. I simply meant that a similar formula is followed to compute time in the Duration class:
https://github.com/Perlence/PyGuitarPro/blob/066ecbf8e75ac85cef0ed3f063d8807c38f97027/guitarpro/models.py#L442
https://github.com/Perlence/PyGuitarPro/blob/066ecbf8e75ac85cef0ed3f063d8807c38f97027/guitarpro/models.py#L450

**Comment by Perlence** [comment]
I see, got it!
