### ISSUE TITLE
Creating custom gp5.file

### ISSUE THREAD

**Issue by tarpalsus** [Perlence/PyGuitarPro#4]
I can't figure out why after song.write() method, all beats seem to be squeezed into one, therefore all notes have same value and start time. If I explore song class directly after creation, everything seems to be fine, but after writing to file and then restoring it with parse method, the above issue occurs. I would much appreciate any help.

**Comment by Perlence** [comment]
Could you share the code you executing prior to `song.write()`?

**Comment by tarpalsus** [comment]
Base song is some song I get from gp5 file, I want it to stay the same, just substitute tracks with my own.
```
    new_track = gm.Track(base_song, name = 'Track1' )
    base_song.tracks = []
    base_song.tracks.append(new_track)
    new_measure = gm.Measure(new_track)
    base_song.tracks[0].measures.append(new_measure)
    new_voice = gm.Voice(new_measure)
    base_song.tracks[0].measures[0].voices.append(new_voice)
    

    for i, sounds in enumerate(splits):
        duration = sounds[1]
        new_duration = gm.Duration(value = duration)
        new_beat = gm.Beat(base_song.tracks[0].measures[0].voices[0],
                           duration = new_duration,
                           start = i*100
                           )
        base_song.tracks[0].measures[0].voices[0].beats.append(new_beat)
        for note in sounds[0]:
            new_note = gm.Note(base_song.tracks[0].measures[0].voices[0].beats[i],
                               value=note[0]
                               string=note[1]
            base_song.tracks[0].measures[0].voices[0].beats[i].notes.append(new_note)
```

**Comment by Perlence** [comment]
Here's the code that works for me:

```python
import guitarpro as gm

splits = [([(0, 6), (2, 5)], 4),
          ([(3, 6), (5, 5)], 4),
          ([(5, 6), (7, 5)], 4),
          ([(0, 6), (2, 5)], 4)]

base_song = gm.Song()
track = gm.Track(base_song, measures=[])
base_song.tracks.append(track)

m = 0  # number of measure to be edited
header = base_song.measureHeaders[m]
measure = gm.Measure(track, header)
track.measures.append(measure)

voice = measure.voices[0]

for i, (notes, duration) in enumerate(splits):
    new_duration = gm.Duration(value=duration)
    new_beat = gm.Beat(voice,
                       duration=new_duration,
                       status=gm.BeatStatus.normal)
    for value, string in notes:
        new_note = gm.Note(new_beat,
                           value=value,
                           string=string,
                           type=gm.NoteType.normal)
        new_beat.notes.append(new_note)
    voice.beats.append(new_beat)

gm.write(base_song, 'tarpalsus.gp5')
```

Important thing to note is that when `Track` is created without `measures` argument, it automatically creates a `MeasureHeader` with a `Measure` that has two `Voice`s in it. Have a look at `__attrs_post_init__` method of `Song`, `Track` and `Measure`.

So in your case, as I've shown above, you should create a track without measures, create a measure from existing measure header, and fill voices with new beats.

**Comment by Perlence** [comment]
I've made some usability enhancements in 9a23096, so now the code can be written as:

```python
import guitarpro as gm

splits = [([(0, 6), (2, 5)], 4),
          ([(3, 6), (5, 5)], 4),
          ([(5, 6), (7, 5)], 4),
          ([(0, 6), (2, 5)], 4)]

base_song = gm.Song()
track = gm.Track(base_song)
base_song.tracks.append(track)
measure = track.measures[0]
voice = measure.voices[0]

for i, (notes, duration) in enumerate(splits):
    new_duration = gm.Duration(value=duration)
    new_beat = gm.Beat(voice,
                       duration=new_duration,
                       status=gm.BeatStatus.normal)
    for value, string in notes:
        new_note = gm.Note(new_beat,
                           value=value,
                           string=string,
                           type=gm.NoteType.normal)
        new_beat.notes.append(new_note)
    voice.beats.append(new_beat)

gm.write(base_song, 'tarpalsus.gp5')
```

**Comment by tarpalsus** [comment]
Thanks, using your solution everything works fine from the Python level, although I can't open files with my GuitarPro (app crashes). Have you tried opening it and if so, which version of GP do you use?

**Comment by Perlence** [comment]
I have Guitar Pro 5.2, it opens the tab just fine.

**Comment by Perlence** [comment]
The fix now is live in v0.4.

**Comment by glouw** [comment]
> Here's the code that works for me:
> 
> ```python
> import guitarpro as gm
> 
> splits = [([(0, 6), (2, 5)], 4),
>           ([(3, 6), (5, 5)], 4),
>           ([(5, 6), (7, 5)], 4),
>           ([(0, 6), (2, 5)], 4)]
> 
> base_song = gm.Song()
> track = gm.Track(base_song, measures=[])
> base_song.tracks.append(track)
> 
> m = 0  # number of measure to be edited
> header = base_song.measureHeaders[m]
> measure = gm.Measure(track, header)
> track.measures.append(measure)
> 
> voice = measure.voices[0]
> 
> for i, (notes, duration) in enumerate(splits):
>     new_duration = gm.Duration(value=duration)
>     new_beat = gm.Beat(voice,
>                        duration=new_duration,
>                        status=gm.BeatStatus.normal)
>     for value, string in notes:
>         new_note = gm.Note(new_beat,
>                            value=value,
>                            string=string,
>                            type=gm.NoteType.normal)
>         new_beat.notes.append(new_note)
>     voice.beats.append(new_beat)
> 
> gm.write(base_song, 'tarpalsus.gp5')
> ```
> 
> Important thing to note is that when `Track` is created without `measures` argument, it automatically creates a `MeasureHeader` with a `Measure` that has two `Voice`s in it. Have a look at `__attrs_post_init__` method of `Song`, `Track` and `Measure`.
> 
> So in your case, as I've shown above, you should create a track without measures, create a measure from existing measure header, and fill voices with new beats.

How would you put this across two measures?

**Comment by virtualdvid** [comment]
@glouw Did you figure out how to put multiple measures in a track? I started with the library a couple of days ago and I'm having problems with it :( Thanks!

**Comment by glouw** [comment]
No @virtualdvid I did not.
