### ISSUE TITLE
Completeness of Artificial Harmonics

### ISSUE THREAD

**Issue by cwitkowitz** [Perlence/PyGuitarPro#40]
Based on the current models for the artificial harmonics, I am wondering if `TappedHarmonic`, `PinchHarmonic`, and `SemiHarmonic` should be inheriting from `ArtificialHarmonic` instead of `HarmonicEffect`? Otherwise, I think the data for these classes may be incomplete, but I could be wrong.

**Comment by Perlence** [comment]
Hey @cwitkowitz! No, I don't think these three should inherit from ArtificialHarmonic. HarmonicEffect is an abstract class that is made specific by the concrete types of harmonics, including NaturalHarmonic. In particular, ArtificialHarmonic has information about the pitch and the octave of the harmonic, and this info is missing from TappedHarmonic, PinchHarmonic, and SemiHarmonic.

<img src="https://github.com/Perlence/PyGuitarPro/assets/1044300/29d179a6-1e90-421d-8494-255a746f5dad" width="584">
