### ISSUE TITLE
obsolete link in readme could be harmful

### ISSUE THREAD

**Issue by guiv42** [Perlence/PyGuitarPro#41]
[readme file](https://github.com/Perlence/PyGuitarPro/blob/master/README.rst) includes a link to the now obsolete home page of TuxGuitar (site in .com.ar).
This domain name has not been maintained by its owner and now redirects user to some unclear succession of web pages. This domain could even be re-used for malicious activities.
So I suggest removing this link.
Note that another [repository](https://github.com/helge17/tuxguitar) now exists in github with the ambition to continue TuxGuitar development, since the original project in SourceForge is no more maintained.

**Comment by Perlence** [comment]
Thanks, I've changed the link to point to the SourceForge page.
