### ISSUE TITLE
double dots are parsed as single dots

### ISSUE THREAD

**Issue by gokhangerdan** [Perlence/PyGuitarPro#42]
I created a tab using tuxguitar and saved it as gp5 file.
I opened the gp5 file with guitarpro.parse but I couldn't find where double dot information stored.
The only relevant information was isDotted=Bool
Than I tried to guitarpro.write the file back so I can see if it really doesn't read double dots.
And I was right it just ignores double dots and uses single dots instead.

**Comment by Perlence** [comment]
Hello @gokhangerdan, have you tried to open the same GP5 file with TuxGuitar to see if the double dots are there?

AFAIK, double dots are not supported in Guitar Pro 3–5. Also, I couldn't find the TuxGuitar code that would store double dots in GP3–5 files via some previously unused bit flags.

**Comment by gokhangerdan** [comment]
Yes as i said; I created the tab with tuxguitar parsed it and rewrote it with pyguitarpro. result was double dot was rewritten as a single dot and a rest added at the end of the bar.

I didnt know gp5 not supporting double dots.

**Comment by Perlence** [comment]
Here's a similar case from earlier: https://github.com/Perlence/PyGuitarPro/issues/23#issuecomment-882377000
