### ISSUE TITLE
support for parsing variable tempo per measure

### ISSUE THREAD

**Issue by ediLq8UqqfHAGypebNTq** [Perlence/PyGuitarPro#44]
Hello, currently if i open gp3 file (or any other version supported) with tempo set per measure, there is no chance to get this information. The only available tempo value is stored in song.tempo. It is set for the whole song and doesn't reflect changes if they are done to the particular measure later on. 

example tab:
![image](https://github.com/user-attachments/assets/2d0bf5bd-6b26-4829-86ea-3026ad538547)
the result of the song.tempo is 120 which is correct if there are no other changes in tempo

expected behaviour:
i assume we should be able to access tempo data through measure object, something like measure.tempo or maybe measure.timeSignature.tempo

**Comment by Perlence** [comment]
Hello, the tempo change is set in a MixTableChange object of a BeatEffect. On the screenshot, the tempo 140 seems to be set in the first beat of the second measure:

```python
song.tracks[0].measures[1].voices[0].beats[0].effect.mixTableChange.tempo
```

Do is work for you?

**Comment by ediLq8UqqfHAGypebNTq** [comment]
> Hello, the tempo change is set in a MixTableChange object of a BeatEffect. On the screenshot, the tempo 140 seems to be set in the first beat of the second measure:
> 
> ```python
> song.tracks[0].measures[1].voices[0].beats[0].effect.mixTableChange.tempo
> ```
> 
> Does it work for you?

Hey, thank you for quick response. Yes, this works perfectly, the only thing is - i have to check that mixTableChange is not empty, otherwise it will throw an error.

```
for beat in voice.beats:
    if beat.effect.mixTableChange:
```
