### ISSUE TITLE
Can it support gt7 and gp8 versions? Or is there any support plan?

### ISSUE THREAD

**Issue by ysho123** [Perlence/PyGuitarPro#45]
Can it support gt7 and gp8 versions? Or is there any support plan?

**Comment by Perlence** [comment]
Hey @ysho123, no, I don't plan to add support for Guitar Pro versions 6 and above.

**Comment by ysho123** [comment]
well,I now want to convert a large number of GP files into MIDI, WAV and XML files for machine learning training. Can you help me in this regard?thx

**Comment by Perlence** [comment]
AFAIK, Guitar Pro 7's gp file is a plain ZIP archive. You can unpack it and find the `score.gpif` file, which is an XML file. You can parse it with [ElementTree](https://docs.python.org/3/library/xml.etree.elementtree.html).

However, the chances of Guitar Pro 8 following the same structure are pretty slim, considering that versions 5, 6, and 7 had very different formats. So you'll probably have to improvise there.
