### ISSUE TITLE
Create ABC music notation just like alphatab does

### ISSUE THREAD

**Issue by japrogramer** [Perlence/PyGuitarPro#5]
https://demo.alphatab.net/alphatex.html#noteeffects

alphatab has a neat output mode, that i would like to get my hands on how to easily transcribe gp5 files into this format. I was hoping that PyGuitarPro has a method to output this same type of text.
better seen here

https://demo.alphatab.net/alphatex.html#exporter

**Comment by Perlence** [comment]
No, unfortunately there's no such method in PyGuitarPro at the moment. But are welcome to contribute it 😊

**Comment by Perlence** [comment]
@japrogramer Seems like this is what you're looking for https://github.com/vladsydorenko/AngelHack/blob/ba83753c6ebb1f34a9be818c2035fb1c9c0bc50a/musichub/track/converter.py

I'll close this, I think ABC notation is not in the scope of the project.
