### ISSUE TITLE
Support for changing tempo?

### ISSUE THREAD

**Issue by brianc118** [Perlence/PyGuitarPro#8]
From the source code there appears to be no support for ritenuto, rallentando etc., though there is support for discrete changes in tempo (in measureHeaders). Am I correct?

**Comment by Perlence** [comment]
The correct way to change tempo is via `MixTableChange`:

```python
tempoChange = MixTableChange(tempo=MixTableItem(value=140, duration=4))
beat.effect.mixTableChange = tempoChange
```

Here we change tempo from previous value to 140 during 4 beats. For example, if tempo was 160 before then it's rallentando, and if we set duration to 0 then it's ritenuto.

The attribute `MeasureHeader.tempo` is deprecated and will be removed in the next release.
