### ISSUE TITLE
WahState. Is 1 a valid value?

### ISSUE THREAD

**Issue by brianc118** [Perlence/PyGuitarPro#9]
Not sure where you originally found the specs for gp5, but is 1 a valid WahState? When parsing some of my files, I'm getting:
`ValueError: 1 is not a valid WahState`

**Comment by Perlence** [comment]
Hey, could you please share one of those tabs that cannot be parsed?

**Comment by Perlence** [comment]
@brianc118 I assume that wah-wah can be of any value between 0 and 100, not strictly "open" or "closed". So yeah, `1` should be a valid state. I implemented this in 89ec9e1, please see if it helps.

**Comment by Perlence** [comment]
Released a new version of PyGuitarPro with this fix.
